version: "3.9"
services:
  http-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NacosAddr=172.31.244.8:8846
      - NacosNamespace=dev
    command: [ "/app/main" ]