version: "3.9"
services:
  sum-srv:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NacosAddr=172.31.244.8:8846
      - NacosNamespace=dev
    command: [ "/app/main" ]